### ISSUE TITLE
for phrase in speech

### ISSUE THREAD

**Issue by lavrenkov-sketch** [cmusphinx/pocketsphinx#215]
I need to make my websocket server which sends recognized phrases. Immediately bring the complete program code

```
`import` asyncio
import websockets
import os
from pocketsphinx import LiveSpeech, get_model_path
model_path = get_model_path()

speech = LiveSpeech(
    verbose=False,
    sampling_rate=16000,
    buffer_size=2048,
    no_search=False,
    full_utt=False,
    hmm=os.path.join(model_path, 'zero_ru.cd_cont_4000'),
    lm=False,
    jsgf=os.path.join(model_path, 'calc2.jsgf'),
    dic=os.path.join(model_path, 'vocabular.dict')
)

async def ph(websocket, path):
    while True:
        print('socket executed')
        for phrase in speech:
            print(phrase)
            await websocket.send(phrase)
            await asyncio.sleep(2)

async def main():  # maybe use this to get/write to the database etc
    while True:  # instead of the loop at bottom
        print('main executed')
        await asyncio.sleep(20)


start_server = websockets.serve(ph, '0.0.0.0', 5678)

asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_until_complete(main())
asyncio.get_event_loop().run_forever()`
```

In this section I want to constantly send the phrase to clients, but for some reason I get an error instead. What am I doing wrong ? Thank you in advance

```
`for phrase in speech:
    print(phrase)
    await websocket.send(phrase)
    await asyncio.sleep(2)`
```

I got this error

```
`Error in connection handler
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/websockets/server.py", line 191, in handler
    await self.ws_handler(self, path)
  File "2.py", line 47, in ph
    await websocket.send(phrase)
  File "/usr/local/lib/python3.8/dist-packages/websockets/protocol.py", line 578, in send
    message_chunk = next(iter_message)
  File "/usr/local/lib/python3.8/dist-packages/pocketsphinx/__init__.py", line 211, in __iter__
    with self.ad:
  File "/usr/local/lib/python3.8/dist-packages/sphinxbase/ad_pulse.py", line 91, in __enter__
    return _ad_pulse.Ad___enter__(self)
RuntimeError: Ad___enter__ returned -1`
```

**Comment by nshmyrev** [comment]
Same as https://github.com/cmusphinx/pocketsphinx-python/issues/63
