### ISSUE TITLE
Building wheel for pocketsphinx5 (pyproject.toml) did not run successfully.

### ISSUE THREAD

**Issue by alekione** [cmusphinx/pocketsphinx#281]
I was tring to install it as you've suggested in README.md file but i got this error. Can you please help me out...
I was running the command ```pip install .```
```
Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pocketsphinx5
  Building wheel for pocketsphinx5 (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pocketsphinx5 (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
        File "/tmp/pip-build-env-sw9cx83b/overlay/local/lib/python3.10/dist-packages/skbuild/setuptools_wrap.py", line 613, in setup
          cmkr = cmaker.CMaker(cmake_executable)
        File "/tmp/pip-build-env-sw9cx83b/overlay/local/lib/python3.10/dist-packages/skbuild/cmaker.py", line 141, in __init__
          self.cmake_version = get_cmake_version(self.cmake_executable)
        File "/tmp/pip-build-env-sw9cx83b/overlay/local/lib/python3.10/dist-packages/skbuild/cmaker.py", line 95, in get_cmake_version
          raise SKBuildError(
      Traceback (most recent call last):
      
      Problem with the CMake installation, aborting build. CMake executable is cmake
      [end of output]
```

**Comment by alekione** [comment]
I,m using kali-linux  5.18.0-kali5-amd64

**Comment by dhdaines** [comment]
Hi, is that really all the output that it gives you?

I don't really know what kali-linux is, but it seems that it is not possible to use scikit-build on it, in which case this is either a bug in kali-linux or in scikit-build.

Please try to [install scikit-build](https://scikit-build.readthedocs.io/en/latest/) and build one of the [sample projects](https://github.com/scikit-build/scikit-build-sample-projects), and if that works, then perhaps there is a problem with PocketSphinx.

**Comment by dhdaines** [comment]
> hi, were you able to solve this problem? I got the same issue today

What OS are you using?  It works on Ubuntu 22.04, 23.10, MacOS 12 and 13, and Windows 10.

From what I know about Kali Linux, which is not much, you shouldn't expect to be able to compile/install things on it, for some [surely very important reasons](https://www.kali.org/docs/introduction/should-i-use-kali-linux/) (though this didn't seem to prevent it being vulnerable to the recent xz backdoor):

**Comment by dhdaines** [comment]
Also make sure you are using the latest version (5.0.3 or the source from git) as the switch to `skbuild-core` seems to have resolved a number of issues.

**Comment by ZouFurong** [comment]
Thank you for you information! Unfortunately I'm using Windows 11 pro.

**Comment by dhdaines** [comment]
Hmmm... can you use the binary packages from PyPI?  `pip install pocketsphinx` ought to work at least.

Building on Windows can be a bit of a black art in general.
