### ISSUE TITLE
ModuleNotFoundError: No module named 'distutils.command.bdist_msi'

### ISSUE THREAD

**Issue by rudrathegreat** [cmusphinx/pocketsphinx#299]
During installation of pocketsphinx, the following message popped up - 

```
Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\rudra\AppData\Local\Temp\pip-install-q_vdyip2\pocketsphinx_6e5f1013aab348c08e35a9913e262b87\setup.py", line 20, in <module>
          from distutils.command.bdist_msi import bdist_msi as _bdist_msi
      ModuleNotFoundError: No module named 'distutils.command.bdist_msi'
```

However, when I manually check to see if the module is installed, it is installed.

Using Windows 11, Python 3.10.2.

**Comment by dhdaines** [comment]
Yes, unfortunately this is a known problem with the old pocketsphinx-python module, which tries to do obsolete and dodgy things when installing on Windows.  Please try the pre-release version (e.g. `pip install --pre pocketsphinx`)
