### ISSUE TITLE
Error installing scipy

### ISSUE THREAD

**Issue by YungAlfa** [cmusphinx/pocketsphinx#312]
**Very** new to this but I am trying to install scipy as a part of quantstats and I am receiving an error message saying requirements to build wheel did not run successfully. Here is the code:

      ../../meson.build:49:0: ERROR: Unknown compiler(s): [['gfortran'], ['flang'], ['nvfortran'], ['pgfortran'], ['ifort'], ['g95']]
      The following exception(s) were encountered:
      Running `gfortran --version` gave "[Errno 2] No such file or directory: 'gfortran'"
      Running `gfortran -V` gave "[Errno 2] No such file or directory: 'gfortran'"
      Running `flang --version` gave "[Errno 2] No such file or directory: 'flang'"
      Running `flang -V` gave "[Errno 2] No such file or directory: 'flang'"
      Running `nvfortran --version` gave "[Errno 2] No such file or directory: 'nvfortran'"
      Running `nvfortran -V` gave "[Errno 2] No such file or directory: 'nvfortran'"
      Running `pgfortran --version` gave "[Errno 2] No such file or directory: 'pgfortran'"
      Running `pgfortran -V` gave "[Errno 2] No such file or directory: 'pgfortran'"
      Running `ifort --version` gave "[Errno 2] No such file or directory: 'ifort'"
      Running `ifort -V` gave "[Errno 2] No such file or directory: 'ifort'"
      Running `g95 --version` gave "[Errno 2] No such file or directory: 'g95'"
      Running `g95 -V` gave "[Errno 2] No such file or directory: 'g95'"
      
      A full log can be found at /private/var/folders/cl/94hztdt14fb5znh35lf95mbc0000gn/T/pip-install-xia20met/scipy_f372bd7d0425455ea0b0defe4147fdbb/.mesonpy-dhnfcjsj/build/meson-logs/meson-log.txt
      + meson setup --native-file=/private/var/folders/cl/94hztdt14fb5znh35lf95mbc0000gn/T/pip-install-xia20met/scipy_f372bd7d0425455ea0b0defe4147fdbb/.mesonpy-native-file.ini -Ddebug=false -Doptimization=2 --prefix=/Library/Frameworks/Python.framework/Versions/3.10 /private/var/folders/cl/94hztdt14fb5znh35lf95mbc0000gn/T/pip-install-xia20met/scipy_f372bd7d0425455ea0b0defe4147fdbb /private/var/folders/cl/94hztdt14fb5znh35lf95mbc0000gn/T/pip-install-xia20met/scipy_f372bd7d0425455ea0b0defe4147fdbb/.mesonpy-dhnfcjsj/build
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/cl/94hztdt14fb5znh35lf95mbc0000gn/T/pip-build-env-v8zr7b03/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 969, in get_requires_for_build_wheel
          with _project(config_settings) as project:
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 135, in __enter__
          return next(self.gen)
        File "/private/var/folders/cl/94hztdt14fb5znh35lf95mbc0000gn/T/pip-build-env-v8zr7b03/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 948, in _project
          with Project.with_temp_working_dir(
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 135, in __enter__
          return next(self.gen)
        File "/private/var/folders/cl/94hztdt14fb5znh35lf95mbc0000gn/T/pip-build-env-v8zr7b03/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 777, in with_temp_working_dir
          yield cls(source_dir, tmpdir, build_dir)
        File "/private/var/folders/cl/94hztdt14fb5znh35lf95mbc0000gn/T/pip-build-env-v8zr7b03/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 682, in __init__
          self._configure(reconfigure=bool(build_dir) and not native_file_mismatch)
        File "/private/var/folders/cl/94hztdt14fb5znh35lf95mbc0000gn/T/pip-build-env-v8zr7b03/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 713, in _configure
          self._meson(
        File "/private/var/folders/cl/94hztdt14fb5znh35lf95mbc0000gn/T/pip-build-env-v8zr7b03/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 696, in _meson
          return self._proc('meson', *args)
        File "/private/var/folders/cl/94hztdt14fb5znh35lf95mbc0000gn/T/pip-build-env-v8zr7b03/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 691, in _proc
          subprocess.check_call(list(args))
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['meson', 'setup', '--native-file=/private/var/folders/cl/94hztdt14fb5znh35lf95mbc0000gn/T/pip-install-xia20met/scipy_f372bd7d0425455ea0b0defe4147fdbb/.mesonpy-native-file.ini', '-Ddebug=false', '-Doptimization=2', '--prefix=/Library/Frameworks/Python.framework/Versions/3.10', '/private/var/folders/cl/94hztdt14fb5znh35lf95mbc0000gn/T/pip-install-xia20met/scipy_f372bd7d0425455ea0b0defe4147fdbb', '/private/var/folders/cl/94hztdt14fb5znh35lf95mbc0000gn/T/pip-install-xia20met/scipy_f372bd7d0425455ea0b0defe4147fdbb/.mesonpy-dhnfcjsj/build']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

I am using pip3 on macOS Big Sur. Any solutions to this would be much appreciated, thanks.

**Comment by dhdaines** [comment]
Hi, I think you reported this to the wrong place, this is for issues installing PocketSphinx, not SciPy, and I don't know what quantstats is either.
