### ISSUE TITLE
Pip install error: fatal error: 'Python.h' file not found

### ISSUE THREAD

**Issue by thomasf1** [cmusphinx/pocketsphinx#321]
Trying to install with 'pip3 install pocketsphinx' on a mac (arm/M1)

Installed the following before:
brew install swig git python3

Update: Solved it: Homebrew actually installs all needed dev headers with pyhton, but my system was using another python version (from miniconda in my case). Needed to install all requirements with 'pip3 install -r requirements.dev.txt' first.

```
      /private/var/folders/ml/wgr9m89112l8l8skrb8xkkp80000gn/T/pip-install-ozg1kh0e/pocketsphinx_f2b7c0d002dd4ac5b4ea97c24566c7fc/_skbuild/macosx-12.0-arm64-3.9/cmake-build/cython/_pocketsphinx.c:6:10: fatal error: 'Python.h' file not found
      #include "Python.h"
               ^~~~~~~~~~
      1 error generated.
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/private/var/folders/ml/wgr9m89112l8l8skrb8xkkp80000gn/T/pip-build-env-l2yiz6fz/overlay/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 640, in setup
          cmkr.make(make_args, install_target=cmake_install_target, env=env)
        File "/private/var/folders/ml/wgr9m89112l8l8skrb8xkkp80000gn/T/pip-build-env-l2yiz6fz/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 669, in make
          self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
        File "/private/var/folders/ml/wgr9m89112l8l8skrb8xkkp80000gn/T/pip-build-env-l2yiz6fz/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 700, in make_impl
          raise SKBuildError(
      
      An error occurred while building with CMake.
        Command:
          cmake --build . --target install --config Release --
        Install target:
          install
        Source directory:
          /private/var/folders/ml/wgr9m89112l8l8skrb8xkkp80000gn/T/pip-install-ozg1kh0e/pocketsphinx_f2b7c0d002dd4ac5b4ea97c24566c7fc
        Working directory:
          /private/var/folders/ml/wgr9m89112l8l8skrb8xkkp80000gn/T/pip-install-ozg1kh0e/pocketsphinx_f2b7c0d002dd4ac5b4ea97c24566c7fc/_skbuild/macosx-12.0-arm64-3.9/cmake-build
      Please check the install target is valid and see CMake's output for more information.
      [end of output]
```

**Comment by dhdaines** [comment]
Glad you found the solution :) what was the problem?

**Comment by dhdaines** [comment]
Ah, I see!  Thanks!

**Comment by thomasf1** [comment]
Thanks. Hope it helps if anyone else has a similar problem :)
