### ISSUE TITLE
Segmentation fault when running tutorial code hello_ps

### ISSUE THREAD

**Issue by steowens** [cmusphinx/pocketsphinx#35]
I am providing output from gdb in order to facilitate more rapid diagnosis of the issue.

```
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i686-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./hello_ps...(no debugging symbols found)...done.
(gdb) r
Starting program: /home/thinkpad/Sphinx/helloWorld/hello_ps 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0xb7fb0acd in ps_process_raw (ps=0xb7fe77aa <_dl_lookup_symbol_x+266>, data=0xbfffedd0, n_samples=512, no_search=0, full_utt=0) at pocketsphinx.c:1077
1077	    if (ps->acmod->state == ACMOD_IDLE) {
(gdb) bt full
#0  0xb7fb0acd in ps_process_raw (ps=0xb7fe77aa <_dl_lookup_symbol_x+266>, data=0xbfffedd0, n_samples=512, no_search=0, full_utt=0) at pocketsphinx.c:1077
        n_searchfr = 0
#1  0x08048917 in main ()
No symbol table info available.
(gdb) Quit
A debugging session is active.

	Inferior 1 [process 31910] will be killed.

Quit anyway? (y or n) y
```

**Comment by steowens** [comment]
Here is the source file that produces the above error.
```
# include <pocketsphinx.h>

int main(int argc, char *argv[]) {
  
	ps_decoder_t *ps;
	cmd_ln_t *config;
	FILE *fh;
	char const *hyp, *uttid;
	int16 buf[512];
	int rv;
	int32 score;
	const char* fileName = "goforward.raw";

	config = cmd_ln_init(NULL, ps_args(), TRUE,
			"-hmm", MODELDIR "/en-us/en-us",
			"-lm", MODELDIR "/en-us/en-us.lm.bin",
			"-dict", MODELDIR "/en-us/cmudict-en-us.dict",
			NULL);
	if(config == NULL)
		return 1;
	
	fh = fopen(fileName, "rb");
	if(fh == NULL){
		fprintf(stderr, "Unable to open: %s", fileName);
		return -1;
	}
	while(!feof(fh)){
		size_t nsamp;
		nsamp = fread(buf, 2, 512, fh);
		rv = ps_process_raw(ps, buf, nsamp, FALSE, FALSE);
	}	
	rv = ps_end_utt(ps);
	if(rv < 0)
		return 1;
	hyp = ps_get_hyp(ps, &score);
	if(hyp == NULL)
		return 1;
	printf("Recognized: %s\n", hyp);
	
	fclose(fh);
	ps_free(ps);
	cmd_ln_free_r(config);
	return 0;
}
```

**Comment by mbait** [comment]
I don't know if it solves the issues, but can change your reading loop to:
    
    while ((n = fread(buf, 2, 512, fh)) > 0) {
         rv = ps_process_raw(ps, buf, n / sizeof *buf, FALSE, FALSE);
    }

At first, this solves the problem with `feof` which only returns positive when the previous operation has failed. Second, `ps_process_raw` accepts number of **samples** to process, while `fread` return the number of **bytes** read.

**Comment by steowens** [comment]
So after chatting with someone on the IRC channel, it appears that I forgot some important crucial steps.  namely I did not call ps_init, nor did I call ps_begin_utterance.  No guards in the code against uninitialized data structures.

```
        ps = ps_init(config);
        if (ps == NULL)
                return 1;
```
```
   rv = ps_start_utt(ps);
        if (rv < 0)
            return 1;
```

**Comment by steowens** [comment]
Adding those into the file I posted above in their correct places resolves the issue.

**Comment by steowens** [comment]
Of course in thinking about this, the simple fix is to initalize the ps pointer in the sample code to NULL, and making sure that the ps_process_raw code checks for null pointers.
An even more elegant solution is if the library were to instantiate the data structure using some kind of factory pattern.  for example:
```
PSHandle ps = ps_create_handle(...);
```
and somewhere in the code ps_process_raw you have something like:
```
if(ps->magic != PS_MAGIC)
  // Report an uninitialized psHandle.
```

**Comment by nshmyrev** [comment]
This is just a typo, there are many ways in C to break things, you need to be more accurate.
