### ISSUE TITLE
Pocketsphinx and Python 3.4 TypeError

### ISSUE THREAD

**Issue by danilopeixoto5** [cmusphinx/pocketsphinx#4]
Directory structure:
```
+---site-packages
    +---Pocketsphinx-1.0.0-py3.4.egg-info (folder)
    +---pockesphinx.dll
    +---sphinxbase.dll
    +---pockesphinx.py
    +---sphinxbase.py
    +---_pockesphinx.pyd
    +---_sphinxbase.pyd
```
``` python
import os
import pyaudio
from pocketsphinx import *
from sphinxbase import *

MODELDIR = "C:/en-us"

config = Decoder.default_config()
config.set_string('-hmm', os.path.join(MODELDIR, 'hmm'))
config.set_string('-dict', os.path.join(MODELDIR, 'lm/dict.dic'))
config.set_string('-lm', os.path.join(MODELDIR, 'lm/lm.dmp'))
decoder = Decoder(config)

p = pyaudio.PyAudio()
 
stream = p.open(format=pyaudio.paInt16, channels=1, rate=16000, input=True, frames_per_buffer=1024)
stream.start_stream()
in_speech_bf = True
decoder.start_utt('')
while True:
    buf = stream.read(1024)
    if buf:
        decoder.process_raw(buf, False, False)
        try:
            if  decoder.hyp().hypstr != '':
                print('Partial decoding result:', decoder.hyp().hypstr)
        except AttributeError:
            pass
        if decoder.get_in_speech():
            sys.stdout.write('.')
            sys.stdout.flush()
        if decoder.get_in_speech() != in_speech_bf:
            in_speech_bf = decoder.get_in_speech()
            if not in_speech_bf:
                decoder.end_utt()
                try:
                    if  decoder.hyp().hypstr != '':
                        print('Stream decoding result:', decoder.hyp().hypstr)
                except AttributeError:
                    pass
                decoder.start_utt('')
    else:
        break
decoder.end_utt()
print('An Error occured:', decoder.hyp().hypstr)
```
Python returns:
```
Traceback (most recent call last):
  File "C:\Users\Danilo\Desktop\decoder_test.py", line 21, in <module>
    decoder.process_raw(buf, False, False)
  File "C:\Python34\lib\site-packages\pocketsphinx.py", line 284, in process_raw
    return _pocketsphinx.Decoder_process_raw(self, *args)
TypeError: in method 'Decoder_process_raw', argument 2 of type 'void const *'
```
```
TypeError: in method 'Decoder_process_raw', argument 2 of type 'void const *'
```
Thanks in advance.

**Comment by nshmyrev** [comment]
Fixed in master, now we support Python 3
